spring.application.name=Elepent
spring.mongodb.uri=mongodb+srv://ravindu:1234@cluster1.9xamarc.mongodb.net/Oop?retryWrites=true&w=majority&appName=Cluster1

logging.level.org.springframework.data.mongodb=DEBUG
